### ISSUE TITLE
Could not determine git flow version

### ISSUE THREAD

**Issue by xiaoyi-coding** [RubinCarter/gitflow4idea-plus#20]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

After starting Goland Idea, the Git-flow plug-in prompts Could not determine Git flow version

The specific mistake was:

```bash
Could not determine git flow version

com.intellij.openapi.vcs.VcsException: git: 'flow' is not a git command. See 'git --help'.

The most similar commands are
reflog
show
	at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:156)
	at git4idea.commands.GitCommandResult.getOutputOrThrow(GitCommandResult.java:145)
	at gitflow.GitflowVersionTester.init(GitflowVersionTester.java:67)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:304)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. ???
3. Profit

* **What is the expected behavior?**

The Git Flow plug-in is working correctly

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.10
  - Gitflow version: run in terminal `>1.12.3 (AVH Edition)`
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
GoLand 2022.2.2
Build #GO-222.3739.57, built on August 17, 2022
Runtime version: 17.0.3+7-b469.37 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )
*

**Comment by lesdekock** [comment]
Hi, 
I had the exactly the same issue after setting up  a new Ubuntu VM for my development environment.

apt install git-glow.

My Environment is now as follows: 

- Gitflow4idea version: 0.7.11
- Gitflow version: run in terminal  1.12.3-3
- PyCharm as follows:
  PyCharm 2022.2.3 (Professional Edition)
  Build #PY-222.4345.23, built on October 11, 2022
  Runtime version: 17.0.4.1+7-b469.62 amd64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  Linux 5.15.0-1022-azure
  GC: G1 Young Generation, G1 Old Generation
  Memory: 1762M
  Cores: 4
  Registry:
      debugger.watches.in.variables=false
  
  Non-Bundled Plugins:
      net.seesharpsoft.intellij.plugins.csv (2.21.0)
      XPathView (222.4345.14)
      IdeaVIM (1.11.1)
      com.microsoft.vso.idea (1.162.0)
      Gitflow-Fix (0.7.11)
      ru.meanmail.plugin.requirements (2022.4)
      net.firebits.odoo (1.2.1)
      dev.ngocta.pycharm-odoo (2022.6.1)
      com.koxudaxi.pydantic (0.3.14)
  
  Current Desktop: ubuntu:GNOME

Issue seems to be resolved.
