### ISSUE TITLE
IDE Internal Error: Could not determine git flow version

### ISSUE THREAD

**Issue by adear11** [RubinCarter/gitflow4idea-plus#24]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
IDE Internal Error is logged when the IDE starts up.

```
Could not determine git flow version

com.intellij.openapi.vcs.VcsException: git: 'flow' is not a git command. See 'git --help'.

The most similar commands are
reflog
show
	at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:156)
	at git4idea.commands.GitCommandResult.getOutputOrThrow(GitCommandResult.java:145)
	at gitflow.GitflowVersionTester.init(GitflowVersionTester.java:67)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:304)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

I am using PHPStorm on Widows with git installed in WSL.
1. Install git in WSL2
2. In PHPStorm, the git executable is set as `\\wsl$\Ubuntu\usr\bin\git`
3. Install git flow AVH via Brew
4. Install Git Flow Integration Plus (0.7.11) plugin
5. Restart IDE

* **What is the expected behavior?**
I expect that the plugin would properly identify the version of git flow installed.

* **Please tell me about your environment:**
  
```
➜  ~ git version
git version 2.25.1
➜  ~ git flow version
1.12.3 (AVH Edition)
```

```
PhpStorm 2022.2.3
Build #PS-222.4345.15, built on October 5, 2022

Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    editor.focus.mode.color.light=6a737d
    ide.editor.tab.selection.animation=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6a737d

Non-Bundled Plugins:
    com.wakatime.intellij.plugin (14.1.1)
    org.intellij.plugins.hcl (222.4345.14)
    com.intellij.ideolog (203.0.30.0)
    org.intellij.plugins.postcss (222.4345.14)
    com.mallowigi (73.0.0)
    de.espend.idea.php.annotation (8.2.3)
    de.espend.idea.laravel (0.15.4)
    intellij.prettierJS (222.4345.14)
    com.nekofar.milad.intellij.nuxtjs (1.2.1)
    com.chrisrm.idea.MaterialThemeUI (7.14.2)
    ir.msdehghan.plugins.ansible (0.92)
    fr.adrienbrault.idea.symfony2plugin (2022.1.235)
    com.atlassian.bitbucket.references (2020.3.206)
    Gitflow-Fix (0.7.11)
    org.jetbrains.plugins.node-remote-interpreter (222.4345.14)
    ru.adelf.idea.dotenv (2022.2)
    com.laravel_idea.plugin (6.0.0.222)
    aws.toolkit (1.52-222)
```

**Comment by lusacramento** [comment]
I have a similar error. However, my git version is 2.34.1
