### ISSUE TITLE
bug report: com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=ProjectName, containerState=DISPOSE_COMPLETED, componentStore=ProjectPath) (disposed) (class com.intellij.openapi.project.impl.ProjectImpl) has already been disposed

### ISSUE THREAD

**Issue by fbreno** [RubinCarter/gitflow4idea-plus#29]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.11
  - Gitflow version:  1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    IntelliJ IDEA 2023.1 (Ultimate Edition)
    Build #IU-231.8109.175, built on March 28, 2023
    Licensed to Fernando Breno
    Subscription is active until October 10, 2023.
    For educational use only.
    Runtime version: 17.0.6+10-b829.5 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
    Windows 11.0
    GC: G1 Young Generation, G1 Old Generation
    Memory: 2048M
    Cores: 8
    Registry:
        debugger.new.tool.window.layout=true
        ide.windowSystem.autoShowProcessPopup=true
        ide.experimental.ui=true
    
    Non-Bundled Plugins:
    com.github.copilot (1.2.4.2459)
    Gitflow-Fix (0.7.11)
    tv.twelvetone.intellij.plugins.intellivue (1.1.31)
    org.intellij.grails (231.8109.90)

    Kotlin: 231-1.8.20-IJ8109.175
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )
* I just opened intellij and this error was shown
* com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=iPathos, containerState=DISPOSE_COMPLETED, componentStore=C:\Projetos\Pathoweb) (disposed) (class com.intellij.openapi.project.impl.ProjectImpl) has already been disposed (see the cause for stacktrace) so the child: gitflow.GitflowVersionTester$$Lambda$2247/0x00000001015e14b0@34dd2c94 (class gitflow.GitflowVersionTester$$Lambda$2247/0x00000001015e14b0) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:164)
	at gitflow.GitflowVersionTester.lambda$forProject$1(GitflowVersionTester.java:24)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at gitflow.GitflowVersionTester.forProject(GitflowVersionTester.java:21)
	at gitflow.ui.GitflowWidget.getHasVersionBeenTested(GitflowWidget.java:291)
	at gitflow.ui.GitflowWidget.getSelectedValue(GitflowWidget.java:144)
	at gitflow.ui.GitflowWidget.getText(GitflowWidget.java:277)
	at com.intellij.openapi.wm.impl.status.TextPresentationComponent.beforeUpdate(IdeStatusBarImpl.kt:848)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.updateWidget$lambda$24(IdeStatusBarImpl.kt:616)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by frague59** [comment]
Same issue here...

**Comment by knechtrootrecht81** [comment]
same here...

**Comment by Rainsheep** [comment]
同样的问题

**Comment by Rainsheep** [comment]
fix this problem, use https://github.com/Rainsheep/gitflow4idea-plus

**Comment by shuohao** [comment]
> fix this problem, use https://github.com/Rainsheep/gitflow4idea-plus

可以提供个打包好的吗
![0104A1CD](https://github.com/RubinCarter/gitflow4idea-plus/assets/4637107/7e8edae7-84a4-4948-9311-dde89f5a711d)

**Comment by shuohao** [comment]
> > > fix this problem, use https://github.com/Rainsheep/gitflow4idea-plus
> > 
> > 
> > 可以提供个打包好的吗 ![0104A1CD](https://user-images.githubusercontent.com/4637107/255089186-7e8edae7-84a4-4948-9311-dde89f5a711d.png)
> 
> 邮箱 我发你

shuohao@126.com 多谢老哥

**Comment by Rainsheep** [comment]
> > > > fix this problem, use https://github.com/Rainsheep/gitflow4idea-plus
> > > 
> > > 
> > > 可以提供个打包好的吗 ![0104A1CD](https://user-images.githubusercontent.com/4637107/255089186-7e8edae7-84a4-4948-9311-dde89f5a711d.png)
> > 
> > 
> > 邮箱 我发你
> 
> [shuohao@126.com](mailto:shuohao@126.com) 多谢老哥

我 oss 加了访问权限，插件的方式不确定是否能用，可以下载本地安装
https://oss.rainsheep.cn/save/gitflow-pro.zip

**Comment by RubinCarter** [comment]
hi, the problem has been fixed, waiting for jetbrains marketplace review
