### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by Remco4EF** [RubinCarter/gitflow4idea-plus#4]
* **I'm submitting a ...**
  - [x ] bug report

* **What is the current behavior?**
During startup of Intellij idea 2021.3.3 you get the following error:

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/roots/impl/ProjectFileIndexImpl.getContentRootForFile must not be null
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.$$$reportNull$$$0(ProjectFileIndexImpl.java)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java)
	at gitflow.GitflowConfigUtil.lambda$init$4(GitflowConfigUtil.java:87)
	at com.intellij.codeWithMe.ClientId$Companion$decorateRunnable$1.run(ClientId.kt:223)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. ???
3. Profit

* **What is the expected behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *find in IntelliJ settings plugins*
  - Gitflow version: run in terminal `>git flow version`
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
JetBrains Rider 2021.3.3
Build #RD-213.6775.4, built on January 26, 2022
Licensed to Remco Blumink
Subscription is active until September 12, 2022.
Runtime version: 11.0.13+7-b1751.25 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 16
Registry:
    ide.mac.bigsur.window.with.tabs.enabled=false
    ide.new.project.model.index.case.sensitivity=true
    ide.images.show.chessboard=true
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false

Non-Bundled Plugins:
    fr.socolin.application-insights-debug-log-viewer (1.3.0)
    com.intellij.resharper.StructuredLogging (2021.3.3.184)
    intellij.prettierJS (213.6461.6)
    com.intellij.resharper.azure (3.50.0.1314-2021.3)
    mobi.hsz.idea.gitignore (4.3.0)
    com.microsoft.vso.idea (1.162.0)
    Gitflow-Fix (0.7.9)

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by RubinCarter** [comment]
I know the cause of the problem, will the problem affect subsequent use?

**Comment by Remco4EF** [comment]
No, it appears not. Looks like the rest is functioning OK!

Tnx anyway for providing a working version of the plugin.. makes life a lot easier.
