### ISSUE TITLE
[BUG] java.lang.Throwable: Assertion failed: dataContext has no component for new ListPopupStep

### ISSUE THREAD

**Issue by CC007** [RubinCarter/gitflow4idea-plus#7]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
I got this stacktrace: 
```
java.lang.Throwable: Assertion failed: dataContext has no component for new ListPopupStep
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:256)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:214)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:181)
	at gitflow.ui.GitflowWidget.getPopupStep(GitflowWidget.java:135)
	at gitflow.ui.GitflowWidget.lambda$getClickConsumer$0(GitflowWidget.java:163)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetWrapper$StatusBarWidgetClickListener.onClick(StatusBarWidgetWrapper.java:169)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Click on the Gitflow button in the taskbar
(I was unable to reproduce the issue, but you as a plugin dev might know what might have happened)

* **What is the expected behavior?**
No errors

* **What is the motivation / use case for changing the behavior?**
Bug free experience without error stacktraces

* **Please tell me about your environment:**
  
  - Gitflow4idea plus version: 0.7.10
  - Gitflow version: 1.12.3 (AVH Edition)
  - IntelliJ version info:

~~~~
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 28, 2022
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 24
Registry:
    tomcat.root.context.by.default=true

Non-Bundled Plugins:
    org.toml.lang (213.5744.224)
    me.laria.code.idea_caseconv (0.7.1)
    in.thekalinga.snippet.intellij (6.1.0)
    com.nerdscorner.android.plugin.github (2.1.1)
    com.euphoricity.gitignore (0.3)
    TunnelliJ (1.0)
    String Manipulation (9.4.0)
    zielu.gittoolbox (212.8.8)
    Gitflow-Fix (0.7.10)
    com.intellij.kubernetes (213.6777.8)
    MavenRunHelper (4.20.213.3714.1)
    com.demonwav.minecraft-dev (2021.3-1.5.18)
    org.rust.lang (0.4.166.4486-213)
    org.intellij.scala (2021.3.20)
    com.intellij.plugins.html.instantEditing (213.5744.122)
    com.haulmont.jpab (2022.1.2-213)
    com.yoheimuta.intellij.plugin.protolint (1.0.1)
    Pythonid (213.6777.52)
    ru.meanmail.plugin.requirements (2022.3-2021.3)

Kotlin: 213-1.6.10-release-961-IJ6777.52
~~~~

**Comment by RubinCarter** [comment]
@CC007 Hello, I have tried all kinds of methods and have not reproduced the problem. Is your problem an inevitable problem? and whether the provided IDEA version number is accurate？

**Comment by CC007** [comment]
All versions provided are accurate. I'll close it for now, until it happens again. At least the problem is now documented.
